services:
  - type: web
    name: digital-legacy-vault
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://digital_legacy_vault_user:password@localhost/digital_legacy_vault
